chore: attempt to help the user if failure finding commits
I experienced a failure due to not setting the fetch-depth to 0
(everything).

It was like this:
  ValueError: SHA b'1234567890123456789012345678901234567890' could not be resolved, git returned: b'1234567890123456789012345678901234567890 missing'

Now print an error suggesting to the user they check their git fetch
depth settings.

Related: #721